# Нагадування по Markdown

Надаємо невелике нагадування записів в
[Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb) (LaTeX):

Markdown | Preview
--- | ---
`**bold text**` | **bold text**
 \\$\frac{x}{y}\\$ | $\frac{x}{y}$
 \\$p^{x}_{y}\\$ | $p^{x}_{y}$
\\$x \cdot y\\$ | $x \cdot y$
\\$\sqrt{x}\\$ | $\sqrt{x}$
\\$\pi\\$ | $\pi$
\\$\approx\\$ | $\approx$

І ще декілька прикладів:

```markdown
$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

 $$
 I =
 \left (\begin{array}{cc}
 1 & 0\\
 0 & 1
 \end{array}\right)
 $$
```

$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

$I =
\left (\begin{array}{cc}
1 & 0\\
0 & 1
\end{array}\right)$
 ---

# Завдання 1.
В шаблоні наведені числові вектори $\overline{a}$ та $\overline{b}$. Порахуй наступне:
- сума $\overline{a}$ та $\overline{b}$
- різниця $\overline{a}$ та $\overline{b}$
- сума $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}^T$.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- добуток Адамара (Hadamard product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.

In [12]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

In [13]:
res = a + b
res

array([[1.5, 3. , 5. , 7. , 9. ]])

In [14]:
res = a - b
res

array([[0.5, 1. , 1. , 1. , 1. ]])

In [15]:
# Пояснення: сума звичайної(1*5) та транспанованої матриці(5*1).

res = a + np.transpose(b)
res

array([[1.5, 2.5, 3.5, 4.5, 5.5],
       [2. , 3. , 4. , 5. , 6. ],
       [3. , 4. , 5. , 6. , 7. ],
       [4. , 5. , 6. , 7. , 8. ],
       [5. , 6. , 7. , 8. , 9. ]])

In [16]:
res = np.dot(a, np.transpose(b))
res

array([[40.5]])

In [17]:
# Пояснення: добуток двох матриць(1*5)
res = np.dot(a, b)
res

ValueError: shapes (1,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

In [18]:
# Пояснення: поелементне множення двох матриць.
res = np.multiply(a, b)
res

array([[ 0.5,  2. ,  6. , 12. , 20. ]])

In [19]:
# Пояснення: поелементне ділення двох матриць.
res = a / b
res

array([[2.        , 2.        , 1.5       , 1.33333333, 1.25      ]])

In [11]:
# Пояснення: поелементне ділення звичайної(1*5) та транспанованої матриці(5*1).
res = a / np.transpose(b)
res

NameError: name 'a' is not defined

# Завдання 2
В цьому завданні ти навчишся перетворювати вектори за допомогою афінних перетворень.  
Дано вектор:
$$
x =
\left(\begin{array}{cc}
2\\
1
\end{array}\right)
$$


Виконай аналітично наступні завдання задавши матрицю перетворення та застосуй її до вектора $x$:

1. Зменши вектор $x$ в 2 рази по вісі $OX$ та збільш в 3 рази по вісі $OY$.
2. Відобрази вектор $x$ відносно початку координат.
3. Перенеси вектор $x$ на -3 по вісі $OX$ та на 1 по вісі $OY$.
4. Змісти вектор $x$ на 60° по вісі $OY$.
5. Поверни вектор $x$ на 30°.
6. Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

In [20]:
import numpy as np

x = np.array([2, 1])

#### 2.1 Зменши вектор  $x$  в 2 рази по вісі  OX  та збільш в 3 рази по вісі  OY .

$$
M_1 =
\left (\begin{array}{cc}
? & ?\\
? & ?
\end{array}\right)
$$

$$
M_1x =
\left(\begin{array}{cc}
? & ?\\
? & ?
\end{array}\right)
\left (\begin{array}{cc}
2\\
1
\end{array}\right)=
\left(\begin{array}{cc}
? \cdot 2 + ? \cdot 1\\
? \cdot 2 + ? \cdot 1
\end{array}\right)=
\left(\begin{array}{cc}
?\\
?
\end{array}\right)
$$

In [21]:
m1 = np.array([[2, 0],
               [0, 3]])

m1_x = np.dot(m1, x)
m1_x

array([4, 3])

#### 2.2 Відобрази вектор $x$ відносно початку координат.

$$
M_2 = ?
\\
M_2x = ?
$$

In [22]:
m2 = np.eye(2, dtype=int)

m2_x = np.dot(m2, x)
m2_x

array([2, 1])

#### 2.3 Перенеси вектор $x$ на -3 по вісі $OX$ та на 1 по вісі $OY$.

$$
M_3 = ?
\\
M_3x = ?
$$

In [23]:
m3 = np.array([[-3, 0],
              [0, 1]])

m3_x = np.dot(m3, x)
m3_x

array([-6,  1])

#### 2.4 Змісти вектор $x$ на 60° по вісі $OY$.


$$
M_4 = ?
\\
M_4x = ?
$$

In [24]:
rad = np.radians(60)

m4 = np.array([[np.cos(rad), -np.sin(rad)],
                [np.sin(rad), np.cos(rad)]])

m4_x = np.dot(m4, x)
m4_x

array([0.1339746 , 2.23205081])

#### 2.5 Поверни вектор $x$ на 30°.

$$
M_5 = ?
\\
M_5x = ?
$$

In [25]:
rad_5 = np.radians(30)

m5 = np.array([[np.cos(rad_5), -np.sin(rad_5)],
                [np.sin(rad_5), np.cos(rad_5)]])

m5_x = np.dot(m5, x)
m5_x

array([1.23205081, 1.8660254 ])

#### 2.6 Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

$$
M_6 = M_5 \cdot M_4 \cdot M_2 \cdot M_1 = ?
$$

$$
M_6 =
\left (\begin{array}{cc}
? & ?\\
? & ?
\end{array}\right)
\\
M_6x = ?
$$

In [27]:
m6 = np.dot(m5, np.dot(m4, np.dot(m2, m1)), d)

m6_x = np.dot(m6, x)
m6_x

array([-3.,  4.])

# Завдання 2 (Альтернативне)

In [ ]:
import cv2 as cv
import urllib
import numpy as np
from google.colab.patches import cv2_imshow as cv_imshow

# Read an image
def read_image_by_url(url):
    req = urllib.request.urlopen(url)
    arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
    img = cv.imdecode(arr, -1)
    return img

url = ''

img = read_image_by_url(url)

In [ ]:
cv_imshow(img)